# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b365e9834aa6850d6a1a33fc66306fdab98a1583105646f84c1f19cb241a9c94ff9dd3ba01c4a1d77b90f798c8e7ec0b23c8219867491ebc7038ac9a918ffc5

test:
  secret_key_base: 9e04c1a5e836ac9ab8b72372805852c58b98bd8298b21d079f1a8f772a1c6d27b137b953485f33b33ec45b916e80f6e64bad97e63e8298ece57f8ca7c524d5ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
